version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: [ '--storageEngine=wiredTiger' ]
    volumes:
      - /home/alwyzon/data:/data/db

  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
