version: '3.8'

services:
  monsoon-frontend:
    build:
      context: .
    image: monsoon-protest-archives:latest
    ports:
      - '3554:3000'
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always
