export const districts = [
  { label: 'Barguna', value: 'Barguna' },
  { label: 'Barisal', value: 'Barisal' },
  { label: 'Bhola', value: 'Bhola' },
  { label: 'Jhalokati', value: 'Jhalokati' },
  { label: 'Patuakhali', value: 'Patuakhali' },
  { label: 'Pirojpur', value: 'Pirojpur' },
  { label: 'Bandarban', value: 'Bandarban' },
  { label: 'Brahmanbaria', value: 'Brahmanbaria' },
  { label: 'Chandpur', value: 'Chandpur' },
  { label: 'Chattogram', value: 'Chattogram' },
  { label: "Cox's Bazar", value: "Cox's Bazar" },
  { label: 'Cumilla', value: 'Cumilla' },
  { label: 'Feni', value: 'Feni' },
  { label: 'Khagrachari', value: 'Khagrachari' },
  { label: 'Lakshmipur', value: 'Lakshmipur' },
  { label: 'Noakhali', value: 'Noakhali' },
  { label: 'Rangamati', value: 'Rangamati' },
  { label: 'Dhaka', value: 'Dhaka' },
  { label: 'Faridpur', value: 'Faridpur' },
  { label: 'Gazipur', value: 'Gazipur' },
  { label: 'Gopalganj', value: 'Gopalganj' },
  { label: 'Kishoreganj', value: 'Kishoreganj' },
  { label: 'Madaripur', value: 'Madaripur' },
  { label: 'Manikganj', value: 'Manikganj' },
  { label: 'Munshiganj', value: 'Munshiganj' },
  { label: 'Narayanganj', value: 'Narayanganj' },
  { label: 'Narsingdi', value: 'Narsingdi' },
  { label: 'Rajbari', value: 'Rajbari' },
  { label: 'Shariatpur', value: 'Shariatpur' },
  { label: 'Tangail', value: 'Tangail' },
  { label: 'Bagerhat', value: 'Bagerhat' },
  { label: 'Chuadanga', value: 'Chuadanga' },
  { label: 'Jashore', value: 'Jashore' },
  { label: 'Jhenaidah', value: 'Jhenaidah' },
  { label: 'Khulna', value: 'Khulna' },
  { label: 'Kushtia', value: 'Kushtia' },
  { label: 'Magura', value: 'Magura' },
  { label: 'Meherpur', value: 'Meherpur' },
  { label: 'Narail', value: 'Narail' },
  { label: 'Satkhira', value: 'Satkhira' },
  { label: 'Jamalpur', value: 'Jamalpur' },
  { label: 'Mymensingh', value: 'Mymensingh' },
  { label: 'Netrokona', value: 'Netrokona' },
  { label: 'Sherpur', value: 'Sherpur' },
  { label: 'Bogura', value: 'Bogura' },
  { label: 'Joypurhat', value: 'Joypurhat' },
  { label: 'Naogaon', value: 'Naogaon' },
  { label: 'Natore', value: 'Natore' },
  { label: 'Chapai Nawabganj', value: 'Chapai Nawabganj' },
  { label: 'Pabna', value: 'Pabna' },
  { label: 'Rajshahi', value: 'Rajshahi' },
  { label: 'Sirajganj', value: 'Sirajganj' },
  { label: 'Dinajpur', value: 'Dinajpur' },
  { label: 'Gaibandha', value: 'Gaibandha' },
  { label: 'Kurigram', value: 'Kurigram' },
  { label: 'Lalmonirhat', value: 'Lalmonirhat' },
  { label: 'Nilphamari', value: 'Nilphamari' },
  { label: 'Panchagarh', value: 'Panchagarh' },
  { label: 'Rangpur', value: 'Rangpur' },
  { label: 'Thakurgaon', value: 'Thakurgaon' },
  { label: 'Habiganj', value: 'Habiganj' },
  { label: 'Moulvibazar', value: 'Moulvibazar' },
  { label: 'Sunamganj', value: 'Sunamganj' },
  { label: 'Sylhet', value: 'Sylhet' },
] as const

export const genders = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
  { label: 'Other', value: 'other' },
] as const

export const incidentTypes = [
  { label: 'Injury', value: 'Injury' },
  { label: 'Death', value: 'Death' },
] as const

export const graphicLevels = [
  { label: 'Moderate', value: 'Moderate' },
  { label: 'Severe', value: 'Severe' },
  { label: 'None', value: 'None' },
] as const

export const userTypes = [
  {
    label: 'admin',
    value: 'admin',
  },
  {
    label: 'user',
    value: 'user',
  },
] as const
